### ISSUE TITLE
Run instructions on Linux?

### ISSUE THREAD

**Issue by qubodup** [shawn42/snelps#5]
Hello,

I can't seem to rake run the game on Arch Linux 64bit.

Any idea how to make it work?

```
    $ rake run --trace 
    (in /home/qubodup/src/git/snelps) 
    ** Invoke run (first_time) 
    ** Execute run 
    rake aborted! 
    uninitialized constant Platform::PLATFORM 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2503:in `const_missing' 
    /home/qubodup/src/git/snelps/lib/platform.rb:6:in `mac?' 
    /home/qubodup/src/git/snelps/Rakefile:31:in `block in <top (required)>' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:634:in `call' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:634:in `block in execute' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain' 
    /usr/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `each' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling' 
    /usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run' 
    /usr/bin/rake:31:in `<main>' 
```

**Comment by shawn42** [comment]
made 1.9 compliant
